config/routes.rb
Kaizano::Application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :events do
    resources :reviews, only: [:index, :show, :create, :new]
    resources :questions, only: [:new, :create]
    resources :multi_choice_questions
  end

  resources :questions do
    resources :question_comments, only: [:new, :create]
    resources :question_answers, only: [:new, :create, :edit, :update]
  end

  resources :multi_choice_questions do 
    resources :multi_choice_answers, only: [:create]
  end

  resources :users, only: [:edit, :update, :show, :destroy, :new]

  resources :how_it_works, only: [:index]

  resources :learn_mores, only: [:index]

  resources :contact_forms, only: [:new, :create] 

  resources :left_feedbacks, only: [:index]

  resources :about_us, only: [:index]

  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  validates_presence_of :first_name
  
  validates_presence_of :last_name
  
  validates_presence_of :email
  
  validates_presence_of :encrypted_password
  
  validates_presence_of :sign_in_count
  
  has_many :events, 
    dependent: :destroy
  
  mount_uploader :avatar, ImageUploader

  validates_length_of :about_me, :maximum => 500

  def each_event_rating_average
    @each_event_rating_average = []
    @all_ratings_from_an_event = []
    events.each do |event|
      if event.reviews.count > 0 
        event.reviews.each do |review|
          @all_ratings_from_an_event << review.rating.to_f 
        end
        review_total = @all_ratings_from_an_event.inject(0) { |sum, review| sum += review }
        @each_event_rating_average << {event.name => (review_total/
        @all_ratings_from_an_event.count).round(2) }
        @all_ratings_from_an_event = []
      end
    end
    @each_event_rating_average
  end

  def calculate_all_presentations_average(all_event_averages)
    if all_event_averages.count > 0
      event_average_totals =[]
      all_event_averages.each do |event|
        event_average_totals << event.values.join.to_f
      end
      average_total = event_average_totals.inject(0) { |sum, review| sum += review }
      (average_total/events_with_reviews_count).round(2)
    else
      "Make Some Events!"
    end
  end

  def events_with_reviews_count
   count = 0
    events.each do |event|
      if event.reviews.count > 0
        count +=1
      end
    end
    count
  end

  def get_highest_rated_presentation(all_event_averages)
    if all_event_averages.count > 0
      events_sorted_by_average = all_event_averages.sort_by { |k| k.values}
      highest_rated = events_sorted_by_average.last
      parse_event_name(highest_rated)
    else 
      "You have no Events!"
    end
  end

  def format_speaker_name
    "#{first_name} #{last_name}"
  end

  def parse_event_name(highest_rated)
    highest_rated_event_name = highest_rated.keys.join
    if highest_rated_event_name.length > 20
      parsed_name = highest_rated_event_name[0..20] + "..."
      "#{parsed_name}, #{highest_rated.values.join}"
    else
      "#{highest_rated_event_name}, #{highest_rated.values.join}"
    end
  end

  def calulate_profile_completion_percent
    precentage_complete = 20
    precentage_complete += 35 if !about_me.nil? && !about_me.blank?
    precentage_complete += 10 if !twitter_handle.nil? && !twitter_handle.blank?
    precentage_complete += 10 if linked_in_url && !linked_in_url.blank?
    precentage_complete += 25 if avatar.present?
    return "#{precentage_complete}%"
  end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :validate_user, :only => :show

  def new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @all_events = current_user.events
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.remove_avatar! if params[:user][:remove_avatar] == "1"
    if params[:commit] == "Save Changes"
      if @user.update(user_params)
        flash[:saved] = "Saved Changes"
        redirect_to  user_path
      else
        render action: 'edit'
      end
    elsif params[:commit] == "Next"
      if !params[:user][:about_me].blank? && @user.update(user_params)
        redirect_to new_event_path
      else
        flash[:add_about_me] = "Must Complete About You to Continue" if params[:user][:about_me].blank?
        render :new
      end
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    if @user.destroyed? 
      flash[:deleted_account] = "Account deleted, we're sorry to lose you."
      redirect_to root_path
    else 
      render :new
    end
  end

  def validate_user
    if !current_user.nil?
      redirect_to root_path unless current_user.id.to_s == params[:id]
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :twitter_handle,
    :linked_in_url, :phone_numer, :about_me, :avatar)
  end
  
end

app/views/users/_events.html.erb
<div class="small-12 medium-10 large-12 columns">
  <table>
    <thead id="events-header">
      <th width="200">Presentation Name</th>
      <th width="200">Number of Reviews</th>
      <th width="250">Presentation Rating</th>
      <th width="125"></th>
      <th width="125"></th>
    </thead>
    <tr id="event-title-future">
      <th align="center" colspan="5"> Future Speaking Events </th>
    </tr>
    <% @all_events.order("event_date").each do |event| %>
      <% if event.event_date > Time.now || event.format_date == Time.now.to_date.strftime("%b %e, %Y")%>
        <td><%=event.parse_name%></td>
          <% if event.count_reviews != 0 %>
            <td align="center"><%= event.count_reviews %></td>
            <td align="center"><%= event.calculate_average_rating %></td>
          <% else %>
            <td align="center"><%= "No Reviews" %></td>
            <td align="center"><%= "No Reviews" %></td>
          <% end %>
        <td align="center"><%= link_to "Edit Event", edit_event_path(event)%></td>
        <td align="center"><%= link_to "View Reviews", event_reviews_path(event) %></td>
      </tr>
      <% end %>
    <% end %>
    <tr id="event-title-past">
      <th align="center" colspan="5"> Past Speaking Events </th>
    </tr>
    <% @all_events.order("event_date DESC").each do |event| %>
      <% if event.event_date < Time.now && event.format_date != Time.now.to_date.strftime("%b %e, %Y")%>
        <td><%=event.parse_name%></td>
          <% if event.count_reviews != 0 %>
            <td align="center"><%= event.count_reviews %></td>
            <td align="center"><%= event.calculate_average_rating %></td>
          <% else %>
            <td align="center"><%= "No Reviews" %></td>
            <td align="center"><%= "No Reviews" %></td>
          <% end %>
          <td align="center"><%= link_to "Edit Event", edit_event_path(event)%></td>
          <td align="center"><%= link_to "View Reviews", event_reviews_path(event) %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/users/_user_dahsh_board_flashes.html.erb
<% if flash[:event_saved] %>
  <div data-alert class="alert-box">
      <%= flash[:event_saved] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if flash[:saved] %>
  <div data-alert class="alert-box">
      <%= flash[:saved] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if flash[:deleted] %>
  <div data-alert class="alert-box">
      <%= flash[:deleted] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/users/_user_stats.html.erb
<div class="row">
  <div class="small-11 medium-8 large-7 columns">
    <div class="stats-tables">
      <ul class="small-block-grid-2 columns">
        <li class="table-data">
          <table height="100">
            <thead >
              <th width="250">Total Presentations</th>
            </thead>
              <tr>
              <td align="center"><%= "#{@all_events.count}" %></td>
              </tr>
          </table>
        </li>
        <li>
          <table height="100">
            <thead class="text-center">
              <th width="250">Presentations with Reviews</th>
            </thead>
              <tr>
                <td align="center"><%= "#{@user.events_with_reviews_count}" %></td>
              </tr>
          </table>
        </li>
         <li>
          <table height="100">
            <thead align="center">
              <th width="250">Average Presentation Rating</th>
            </thead>
              <tr>
              <td align="center"><%= "#{@user.calculate_all_presentations_average(@user.each_event_rating_average)}" %></td>
          </table>
        </li>
        <li>
          <table height="100">
            <thead align="center">
              <th width="250">Highest Rated Presentation</th>
            </thead>
              <tr>
              <td align="center"><%= "#{@user.get_highest_rated_presentation(@user.each_event_rating_average)}" %></td>
              </tr>
          </table>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="panel small-11 small-centered medium-7 large-5 columns">
    <h2 class="sign-up-title">Edit Profile</h2>
      <%= simple_form_for(@user) do |f| %>
        <%= f.input :first_name %><br/>
        <%= f.input :last_name%><br/>
        <%= f.input :about_me, label: "About you (500 character max)", as: :text%><br/>
        <%= f.label "Profile Photo"%><br>
        <%= f.file_field :avatar%><br>
        <label>
          <%= f.check_box :remove_avatar %>
          Remove Avatar?
        </label>
        <%= f.input :twitter_handle, label: 'Twitter Url'%><br/>
        <%= f.input :linked_in_url, label: 'LinkedIn Url'%><br/>
        <div class="row">
          <div class="row">
            <div class="large-6 medium-6 columns">
              <div class="full-length-button">
                <%= f.submit 'Save Changes',class: "button" %>
              </div>
            </div>
            <div class="large-6 medium-6 columns">
              <div class="full-length-button">
                <%= link_to "Cancel", user_path, class: "button" %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="row">
          <div class="large-6 columns">
            <h6><%= link_to "Delete Account", @user, method: :delete, data: { confirm: 'Are you sure you want to delete your account?' } %></h6>
          </div>
        <div>
      </div> 
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="panel small-11 small-centered medium-7 large-5 columns">  
    <div class="row">
      <h2 class="new-event-title">About You</h2>
      <h5><i>Let the audience know who you are.</i></h5>
      <%= simple_form_for(@user) do |f| %>
        <div class="error">
          <%= f.input :about_me, label: false %>
        </div>
        <% if flash[:add_about_me] %>
          <small class="error"><%= flash[:add_about_me] %></small>
        <% end %>
        <div class="submit-button-about-me">
          <div class="full-length-button">
            <%= f.submit 'Next',class: "button" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'user_dahsh_board_flashes' %>
<div class="row">
  <div class="small-11 medium-3 large-4 columns">
    <div class="photo">
      <%= image_tag @user.avatar.thumb.url, class: "profile-pic" %>
    </div>
    <h1><%= @user.format_speaker_name %></h1>
  </div>
  <%= render "user_stats" %>
</div>
<% if @user.calulate_profile_completion_percent != "100%" %>
  <div class="row">
    <div class="small-12 medium-6 large-6 columns">
      <div class="percentage-complete-statement">
        <%= "Your Profile is #{@user.calulate_profile_completion_percent} complete." %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-12 medium-4 large-4 columns">
      <div class="progress [secondary alert success] [radius round]">
        <span class="meter" style="width: <%= "#{@user.calulate_profile_completion_percent}" %>"</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
      <div class="edit-pofile">
        <%= link_to "Complete Profile", edit_user_path(@user) %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="small-12 columns">
      <div class="edit-pofile">
        <%= link_to "Edit Profile", edit_user_path(@user) %>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="large-4 medium-4 small-12 columns">
    <div class="full-length-button">
      <%= link_to "Add Speaking Event", new_event_path, class: "button" %>
    </div>
  </div>
</div>
<div class="row">
  <%= render 'events' %>
</div>