config/routes.rb
Kaizano::Application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :events do
    resources :reviews, only: [:index, :show, :create, :new]
    resources :questions, only: [:new, :create]
    resources :multi_choice_questions
  end

  resources :questions do
    resources :question_comments, only: [:new, :create]
    resources :question_answers, only: [:new, :create, :edit, :update]
  end

  resources :multi_choice_questions do 
    resources :multi_choice_answers, only: [:create]
  end

  resources :users, only: [:edit, :update, :show, :destroy, :new]

  resources :how_it_works, only: [:index]

  resources :learn_mores, only: [:index]

  resources :contact_forms, only: [:new, :create] 

  resources :left_feedbacks, only: [:index]

  resources :about_us, only: [:index]

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="header-home">
  <% if flash[:deleted_account] %>
    <div data-alert class="alert-box">
      <%= flash[:deleted_account] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
  <div class="container-home">
    <div class="small-11 medium-8 large-7 push-1 columns"> 
      <div class="row">
        <div class="title-home">
          <font class="sub-header1">Hone your Presentation Skills</font>
        </div>
      </div>
      <div class="row">
        <div class="title-home">
          <font class="sub-header2"><i>We Make it Easy to Connect with your Audience and Improve your Presentation Skills.</i></font>
        </div>
      </div>
      <div class="row">
        <div class="small-11 medium-11 large-8 columns">
          <div id="home_buttons"> 
            <% if user_signed_in? %>
              <div class="row">
                <div class="row">
                  <div class="medium-6 large-6 columns">
                    <div class="full-length-button">
                      <%= link_to 'Create an Event', new_event_path, class: "button round" %>
                    </div>
                  </div>
                  <div class="medium-6 large-6 columns">
                    <div class="full-length-button">
                      <%= link_to 'Join a Presentation', events_path, class: "button round" %>
                    </div>
                  </div>
                </div>
              </div>
            <% else %>
              <div class="row">
                <div class="row">
                  <div class="medium-12 large-6 columns">
                    <div class="full-length-button">
                      <%= link_to 'Create an Event', new_user_registration_path, class: "button round" %>
                    </div>
                  </div>
                  <div class="medium-12 large-6 columns">
                    <div class="full-length-button">
                      <%= link_to 'Join a Presentation', events_path, class: "button round" %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 medium-4 large-4 columns">
    <div id="icons">
      <i class="fi-torsos-all size-20"></i>
      <h1>Connect</h1>
    </div>
    <font class="title-home">Connect with your audience during and after your presentation.</font>
  </div>
  <div class="small-12 medium-4 large-4 columns">
    <div id="icons">
      <i class="fi-comments size-20"></i>
      <h1>Feedback</h1>
    </div>
    <font class="title-home"> 
      Receive honest feedback from your audience.
    </font>
  </div>
  <div class="small-12 medium-4 large-4 columns">
    <div id="icons">
      <i class="fi-graph-trend size-20"></i>
      <h1>Analytics</h1>
    </div>
      <font class="title-home">Get analytics on all your presentations, see where you're falling short and track your improvement.</font>
  </div>
</div>
<div id="home_button_get_started">
  <div class ="row">
    <div class="small-11 medium-6 large-6 small-centered columns">
      <div class="full-length-button">
        <% if user_signed_in? %>
          <%= link_to "Get Started Today!", new_event_path, class: "button round" %>
        <% else %>
          <%= link_to "Get Started Today!", new_user_registration_path, class: "button round" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="name">
  <div id="footer" style="background-color:#000000;">
    <div class="row">
      <div class="small-11 medium-10 large-11 columns">
        <div class="name-wrapper">
          <font id="name">&copy; 2014 Kaizano inc.</font>
        </div>
      </div>
    </div>
  </div>
</div>