config/routes.rb
Kaizano::Application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :events do
    resources :reviews, only: [:index, :show, :create, :new]
    resources :questions, only: [:new, :create]
    resources :multi_choice_questions
  end

  resources :questions do
    resources :question_comments, only: [:new, :create]
    resources :question_answers, only: [:new, :create, :edit, :update]
  end

  resources :multi_choice_questions do 
    resources :multi_choice_answers, only: [:create]
  end

  resources :users, only: [:edit, :update, :show, :destroy, :new]

  resources :how_it_works, only: [:index]

  resources :learn_mores, only: [:index]

  resources :contact_forms, only: [:new, :create] 

  resources :left_feedbacks, only: [:index]

  resources :about_us, only: [:index]

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  validates_presence_of :name
  
  validates_presence_of :description
  
  validates_length_of :description, :maximum => 500
  
  validates_presence_of :event_password
  
  validates_presence_of :event_date
  
  validates :event_password, uniqueness: true
  
  belongs_to :user
  
  has_many :reviews, 
    dependent: :destroy

  has_many :questions, 
    dependent: :destroy
  
  has_many :multi_choice_questions, 
    dependent: :destroy
  
  validates_length_of :event_password, :maximum => 8
  
  def self.search(search)
    if search != nil
      Event.where("event_password like ?", "#{search}")
    end
  end

  def calculate_average_rating
    @all_reviews = []
    review_count = count_reviews
    reviews.each do |review|
      @all_reviews << review.rating.to_f
    end
    ratings_total = @all_reviews.inject(0) { |sum, rating| sum += rating }
    (ratings_total/review_count).round(2)
  end

  def count_reviews
    reviews.count
  end

  def count_questions
    multi_choice_questions.count
  end

  def question_number(question)
    all_questions = multi_choice_questions.load
    return all_questions.index(question) + 1
  end

  def format_speaker_name
    "#{user.first_name} #{user.last_name}"
  end

  def format_date
    event_date.to_date.strftime("%b %e, %Y")
  end

  def any_multi_choice_questions?
    if multi_choice_questions.count > 0
      true
    else
      false
    end
  end

  def parse_name
    event_name = name
    if event_name.length > 15
      "#{event_name[0..15]}" + "..."
    else
      "#{event_name}"
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :does_user_own_event, :only => [:edit]
  before_filter :did_they_enter_password?, only: [:show]
  before_filter :have_they_answered_multi_choice_questions?, only: [:show]
  before_filter :do_they_have_about_me?, only: [:new, :create]

  def index
    session[:events_authenticated] = [] if session[:events_authenticated].nil?
    if params[:search]
      @event = Event.find_by(event_password: params[:search][:event_password])
      if @event.nil?
        flash[:could_not_find_event_notice] = "Password does not match any events."
        redirect_to events_path
      else
        session[:events_authenticated] << @event.id.to_s
        redirect_to event_path(@event)
      end
    end
  end
  
  def new
    @user = current_user
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:event_saved] = "Event Saved Successfully"
      redirect_to new_event_multi_choice_question_path(@event)
    else
      render :new
    end
  end

  def show
    @question_comment = QuestionComment.new
    @question = Question.new
    @multi_choice_answer = MultiChoiceAnswer.new
    @event = Event.find(params[:id])
    @multi_choice_question = @event.multi_choice_questions.first
  end

  def edit
    @event = Event.find(params[:id])
    if @event.multi_choice_questions.count > 0
      @multi_choice_questions = @event.multi_choice_questions.first
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:saved] = "Saved Changes"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id]).destroy
    flash[:deleted] = "Deleted Event"
    redirect_to user_path(current_user)
  end

  def does_user_own_event
    all_event_ids = []
    current_user.events.each do |event|
      all_event_ids << event.id.to_s
    end
    redirect_to user_path(current_user) unless all_event_ids.include?(params[:id])
  end

  def did_they_enter_password?
    if !session[:events_authenticated].present?
      session[:events_authenticated] = []
    end
    if current_user.nil?
      render status: 404 unless session[:events_authenticated].include?(params[:id])
    else 
      event = Event.find(params[:id])
      render status: 404 unless current_user.id == event.user_id || 
      session[:events_authenticated].include?(params[:id])
    end
  end

  def have_they_answered_multi_choice_questions?
    if !session[:answered_multi_choice].present?
      session[:answered_multi_choice] = []
    end
  end

  def do_they_have_about_me?
    redirect_to new_user_path if current_user.about_me.nil? || current_user.about_me.blank?
  end

  private

  def event_params
    params.require(:event).permit(:name, :user_id, :event_password, :location, :event_date, 
    :event_url, :description, :time)
  end

end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_edit_event_flashes.html.erb
<% if flash[:answered_questions] %>
  <div data-alert class="alert-box">
    <%= flash[:answered_questions] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if flash[:question_saved] %>
  <div data-alert class="alert-box">
    <%= flash[:question_saved] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if flash[:deleted_question] %>
  <div data-alert class="alert-box">
    <%= flash[:deleted_question] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/events/_event_show_page_flash_messages.html.erb
<% if flash[:review_saved] %>
  <div data-alert class="alert-box">
    <%= flash[:review_saved] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if flash[:answered_questions] %>
  <div data-alert class="alert-box">
    <%= flash[:answered_questions] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render 'edit_event_flashes' %>
<div class="row">
  <div class="small-11 medium-7 large-11 small-centered columns">
    <div class="back-link">
      <%= link_to "Back to Dashboard", user_path(current_user) %>
    </div>
  </div>
</div>
<div class="row small">
  <div class="panel small-11 medium-7 large-11 small-centered columns">
    <h2>Edit Event Details</h2>
    <h5 class="delete-event"><%= link_to "Delete Event", @event, method: :delete, data: { confirm: 'Are you sure?  All reviews and questions will also be deleted.' } %></h5>
    <%= simple_form_for(@event) do |f| %>
      <div class="row">
        <div class="large-12 columns">
          <div class="row">
            <div class="large-3 columns">
              <%= f.input :name %>
            </div>
            <div class="large-3 columns">
              <%= f.input :location %>
            </div>
            <div class="large-3 columns">
              <%= f.input :event_url %>
            </div>
            <div class="large-3 columns">
              <%= f.input :event_password, as: :text %>
            </div>
          </div>
          <div class="row">
            <div class="large-4 columns">
              <%= f.input :event_date, label: "Date", as: :date, start_year: Date.today.year, order: [:month , :day, :year], :prompt => {:day => 'Day', :month => 'Month', :year => 'Year'}  %>
            </div>
            <div class="large-8 columns">
              <div id="edit-event-description">
                <%= f.input :description; %>
              </div>
            </div>
            <% if @event.any_multi_choice_questions? %>
              <div class="large-12 columns">
                <h4>Multiple Choice Questions</h4>
              </div>
              <div class="large-12 columns">
                <h5><%= link_to "Add New Question", new_event_multi_choice_question_path(@event) %></h5>
              </div>
              <div class="large-12 columns">
                <table>
                  <tbody>
                    <% @event.multi_choice_questions.each do |question| %>
                      <tr>
                        <td width="875"><%= question.question_body %></td>
                        <td align="center"><%= link_to "Edit", edit_event_multi_choice_question_path(@event, question) %></td>
                      <tr>
                      <% end %>
                    </tr>
                  </tbody>
                </table>
              </div>
            <% else %>
              <div class="large-12 columns">
                <h5 id="add_multi_choice_no_questions"><%= link_to "Add Multiple Choice Question", new_event_multi_choice_question_path(@event) %></h5>
              </div>
            <% end %>            
            <div class="large-6 medium-6 columns">
              <div class="full-length-button">
                <%= f.submit 'Save Changes',class: "button" %>
              </div>
            </div>
            <div class="large-6 medium-6 columns">
              <div class="full-length-button">
                <%= link_to "Cancel", user_path(current_user), class: "button" %>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="find-event-container">
  <div class="panel small-11 small-centered medium-5 large-4 columns">
    <% if @event == nil %>
      <div class="password-title">
        <div class="row">
          <div class="center">
            <h2>Enter Event Password</h2>
          </div>
        </div>
      </div>
      <%= simple_form_for :search, action: events_path, method: "get" do |f| %><br>
        <div class="field-for-password">
          <div class="row">
            <div class="centered">
              <%= f.input :event_password, label: false %>
            </div>
          </div>
        </div>
        <div class="full-length-button">
          <div class="row">
            <%= submit_tag "Find Event", class: "button" %><br>
          </div>
        </div>
        <div class="flash-message">
          <div class="row">
            <%= flash[:could_not_find_event_notice] %>      
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="panel small-11 small-centered medium-7 large-5 columns">  
    <div class="row">
      <h2 class="new-event-title">Create New Speaking Event</h>
    </div>
    <%=simple_form_for(@event) do |f|%>
      <div class="row">
        <%= f.input :name, label: "Event Name" %>
      </div>
      <div class="row">
        <%= f.input :event_password %>
      </div>
      <div class="row">
        <%= f.input :location %>
      </div>
      <div class="row">
        <%= f.input :event_url %>
      </div>
      <div class="row">
        <%= f.input :event_date, label: "Date", as: :date, start_year: Date.today.year, order: [:month , :day, :year], :prompt => {:day => 'Day', :month => 'Month', :year => 'Year'}  %>
      </div>
      <div class="row">
        <%= f.input :description, label: "Event Description (500 characters max)" %>
      </div>
      <div class="row">
        <div class="full-length-button">
          <%=f.submit 'Create Event', class: "button"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<%= render 'event_show_page_flash_messages' %>
<div class="row">
  <div class="small-11 medium-6 large-6 columns">
    <div class="title">
      <h1 class="event-header"><%= @event.name %></h1>
      <h4>Speaker: <%= @event.format_speaker_name %></h4>
      <% if !@event.event_date.nil? %>
        <h6>Date: <%= @event.format_date %></h6>
      <% end %>
      <%if @event.user.about_me != ''%>
        <ul class="inline-list">
          <% if @event.user.twitter_handle != '' %>
          <li>
            <%= link_to simple_format('<i class="fa fa-twitter fa-2x"></i>'),
              @event.user.twitter_handle, target: '_blank' %>
          </li>
          <% end %>
          <%if @event.user.linked_in_url != '' %>
          <li>
            <%= link_to simple_format('<i class="fa fa-linkedin-square fa-2x"></i>'),
              @event.user.linked_in_url, target: '_blank' %>
          </li>
          <%end%>
        </ul>
        <h5 class="event-header">About <%= @event.user.first_name %>:</h5> 
        <h6><%= @event.user.about_me %></h6>
      <%end%>
    </div>
    <div class="row">
      <div class="small-11 medium-11 large-12 columns">
        <h5 class="event-header"> Presentation Description </h5>
        <h6><%=@event.description%></h6>
      </div>
    </div>
  </div>
  <div class-"row">
    <div class="small-12 medium-6 large-6 columns">
      <div class="feedback-button">
        <%= link_to 'Give Feedback', new_event_review_path(@event), class: "button round" %>
      </div>
        <% if @event.multi_choice_questions.present? && !session[:answered_multi_choice].include?(@event.id)  %>
          <div class="answer-questions-button">
            <%= link_to 'Answer Speaker Questions', event_multi_choice_question_path(@event, @multi_choice_question), class: "button round" %>
          </div>
          <div class="row">
            <div class="small-12 small-centered medium-6 medium-centered large-5 large-centered columns">
            </div>
          </div>
        <% end %>
        <h4 id="ask_question_header">Ask a Question</h4>
        <%= simple_form_for ([@event, @question]) do |f| %>
          <%= f.input :body, label: false, as: :text %>
          <%=f.submit "Ask Question",class: "button" %><br>
          <%=flash[:question_added]%>
          <%=flash[:question_can_not_be_blank]%>
        <% end %>
      </div>
    </div>
  </div>
</div>                
<div class="row">
  <div class="small-11 medium-10 large-6 columns">
    <h1 class="event-header">Audience Questions</h1>
  </div>
</div>
<div class="question-object">
  <% @event.questions.each do |question| %>
  <div class="row">
    <div class="small-12 medium-11 large-12 columns">
    <h4><%=question.body%></h4>
   </div>
  </div>
  <div class="row">
    <div class="small-12 medium-12 large-12 columns">
    <a class="answer-link" href="#">Speaker Answer</a><br><br>
    <a class="comment-link" href="#">Comments</a>
      <div class="row">
        <div class="small-12 medium-10 large-12 columns">
            <div class="answer-feed hide">
            <% if !question.question_answer.nil? %>
              <div class="answer-body">
                <h5><%= question.question_answer.answer_body %></h5>
                <h6><i><%="#{question.question_answer.updated_at.to_date.strftime("%m/%d/%Y")}" %></i></h6>
              </div>
            <% else %>
              <div class="no-answer-message">
                <h5><%= "The Presentor has not Answered this Question yet." %></h5>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="small-12 medium-8 large-9 columns">
          <div class="comment-object hide">
            <div class="comment-feed">
              <% if question.question_comments.count > 0 %>
                <% question.question_comments.each do |comment| %>
                  <div class="comment-body">
                   <h6><%="- #{comment.body}"%></h6>
                  </div>
                <% end %>
              <% else %>
                <div class="no-comments-message">
                  <%= "No Comments" %><br>
                </div>
              <% end %>
            </div>
            <%= simple_form_for ([question, @question_comment]) do |f|%>
              <%= f.input :body, label: "Comment", as: :text %>
              <div class="comment-button">
                <%= f.submit "Comment", class: "button tiny"%>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-12 medium-12 large-12 columns">
      <hr>
    </div>
  </div>
<% end %>
</div>