config/routes.rb
Kaizano::Application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :events do
    resources :reviews, only: [:index, :show, :create, :new]
    resources :questions, only: [:new, :create]
    resources :multi_choice_questions
  end

  resources :questions do
    resources :question_comments, only: [:new, :create]
    resources :question_answers, only: [:new, :create, :edit, :update]
  end

  resources :multi_choice_questions do 
    resources :multi_choice_answers, only: [:create]
  end

  resources :users, only: [:edit, :update, :show, :destroy, :new]

  resources :how_it_works, only: [:index]

  resources :learn_mores, only: [:index]

  resources :contact_forms, only: [:new, :create] 

  resources :left_feedbacks, only: [:index]

  resources :about_us, only: [:index]

  

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_filter :does_user_own_event, only: [:index]
  before_filter :have_they_entered_password?, only: [:new]

  def index
    @event = Event.find(params[:event_id])
    @reviews = @event.reviews
    @multi_choice_questions = @event.multi_choice_questions
  end

  def new
    @event = Event.find(params[:event_id])
    @review = @event.reviews.build
  end

  def create
    @event = Event.find(params[:event_id])
    @review = @event.reviews.build(review_params)
    if @review.save
      event_id = params[:event_id]
      session["#{event_id}"] = "added review"
      flash[:review_saved] = "Review Added, Thanks."
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def does_user_own_event
    if user_signed_in?
      all_event_ids = []
      current_user.events.each do |event|
        all_event_ids << event.id.to_s
      end
      redirect_to user_path(current_user) unless all_event_ids.include?(params[:event_id])
    else
      redirect_to root_path
    end
  end

  def have_they_entered_password?
    if session[:events_authenticated].present? && !user_signed_in?
      render status: 404 unless session[:events_authenticated].include?(params[:event_id])
      event_id = params[:event_id]
      if session["#{event_id}"].present?
        redirect_to left_feedbacks_path
      end
    elsif user_signed_in?
      signed_in_user_authentication
    else
      render status: 404
    end
  end

  def signed_in_user_authentication
    event_id = params[:event_id]
    if session["#{event_id}"].present?
      redirect_to left_feedbacks_path
    else
      event = Event.find(params[:event_id])
      render status: 404 unless current_user.id == event.user_id ||
      session[:events_authenticated].include?(params[:event_id])
    end
  end

  private

  def review_params
    params.require(:review).permit(:feedback_comments, :rating, :event_id)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/index.html.erb
<% if flash[:answer_saved] %>
  <div data-alert class="alert-box">
      <%= flash[:answer_saved] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<div class="row">
  <div class="small-4 columns">
    <div class="back-button"><%= link_to "Back to Dashboard", user_path(current_user) %></div>
  </div>
</div>
<div class="row">
  <div class="large-4 small-12 columns">
    <h1 class="title"><%= @event.name %><h1>
  </div>
  <div class="event-tables">
    <div class="large-4 columns">
      <table height="100">
        <thead align="center">
          <th width="250">Ratings Recieved</th>
        </thead>
          <tr>
          <% if @event.count_reviews > 0 %>
            <td align="center"><%= @event.count_reviews %></td>
          <% else %>
            <td>No Ratings Recieved</td>
          </tr>
          <% end %>
        </table>
      </div>
      <div class="large-4 columns">
      <table height="100">
        <thead align="center">
          <th width="250">Average Rating</th>
        </thead>
          <tr>
          <% if @event.count_reviews > 0 %>
            <td align="center"><%= @event.calculate_average_rating %></td>
          <% else %>
            <td>No Ratings Recieved</td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-11 large-12 columns">
    <h6><%= @event.description%></h6>
  </div>
</div>
<div class="row">
  <div class="small-11 large-12 columns">
    <div class="feedback-table">
      <table height="50">
        <thead>
          <th class="table-header" width="915">
            <span>Audience Feedback Comments</span>
            <a class="feedback-link" href="#">View Feedback</a>
          </th>
        </thead>
          <tbody class="feedback-table-content hide">
            <% if @event.reviews.count > 0 %>
              <% @event.reviews.each do |review| %>
                <% if review.feedback_comments != '' %>
                  <tr>
                    <td><%= review.feedback_comments %></td>
                  </tr>
                <% end %>
              <% end %>
            <% else %>
            <tr>
            <td>Audience Members left no feedback</td>
            </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-11 large-12 columns">
    <table height="50">
      <thead>
        <th class="table-header" width="750">
          <span>Audience Questions</span>
          <a class="question-link" href="#">View Questions</a>
        </th>
        <th width="163">
        </th> 
      </thead>
        <tbody class="question-table-content hide">
        <% if @event.questions.count > 0 %>
          <% @event.questions.each do |question| %>
          <tr>
            <td><%= question.body %></td>
            <td align="center">
            <br>
            <div class="comment-button">
              <% if question.question_answer.nil? %>
                <%= link_to "Answer Question", new_question_question_answer_path(question), class: "button tiny" %>
              <% else %>
                <%= link_to "Edit Answer", edit_question_question_answer_path(question, question.question_answer), class: "button tiny" %>
              <% end %>
            </div>
            </td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No Questions</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% if !@multi_choice_questions.first.nil? %>
  <div class="row">
    <div class="small-11 large-12 columns">
      <table height="50">
        <thead>
          <th class="table-header" width="580">
            <span>Multiple Choice Question Results</span>
            <a class="multi-choice-link" href="#">Show Results</a>
          </th>
          <th width="170">
            <span>Answers Submitted</span>
          </th> 
          <th width="163">
            <span>Correct Answer %</span>
          </th> 
        </thead>
        <tbody class="multi-choice-table-content hide">
          <% @multi_choice_questions.each do |question| %>
            <tr>
              <td width="580">
                <div class="row">
                  <div class="small-12 columns">
                    <%= question.question_body %>
                  </div>
                </div>
                <% if question.any_answers? %>
                  <div class="row">
                    <div class="small-12 columns">
                      <%= link_to "Answer Break Down", event_multi_choice_questions_path(question) %>
                    </div>
                  </div>
                <% end %>
              </td>
              <td class="percent-correct" width="170"><%= question.count_answers %></td>
              <td class="percent-correct" width="163"><%= question.check_for_answers %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/reviews/new.html.erb
 <div class="container">
  <div class="panel small-11 small-centered medium-6 large-5 columns"> 
    <h2>Review Presentation</h2>
    <%= simple_form_for ([@event, @review]) do |f| %>
      <div class="row">
        <div class="small-6">
          <div class="rate-presentation">
          <%= f.input :rating, label: "Rating (10 is the highest rating)",
          :collection => 1..10, :include_blank => true  %>
        </div>
      </div>
    </div>
    <div class="feedback-form">
      <%= f.input :feedback_comments, label: "General Feedback Comments", as: :text %>
    </div>
    <div class="row">
      <div class="full-length-button">
        <%= f.submit "Give Review",class: "button" %>
      </div>
    </div>
    <% end %>
  </div>
</div>